import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="m-5 flex flex-row gap-5">
          <Link className="bg-slate-500 p-5 rounded-xl hover:bg-slate-300 transition-colors" href={"/agregar"}>Agregar moto</Link>
          <Link className="bg-slate-500 p-5 rounded-xl hover:bg-slate-300 transition-colors" href={"/motos"}>Listar motos</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
